// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	COS_TESTCASES: KVNamespace;
	ANTHROPIC_API_KEY: string;
	TOKEN_KEY: string;
	SALT: string;
	DB: D1Database;
}
