#:schema node_modules/wrangler/config-schema.json
name = "cos"
main = "src/index.ts"
compatibility_date = "2024-09-24"

assets = { directory = "public" }

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "CHUO_IDS_COS"
database_id = "0903c38e-ec9a-417d-b54a-78704a8cb3a6"

[[kv_namespaces]]
binding = "COS_CASE"
id = "94586c23793b4086ba41f52a893e2cdf"

[observability]
enabled = true
